<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CreateUser_TextNote_TextField</name>
   <tag></tag>
   <elementGuidId>391b86b6-3567-4e90-9ddc-9dffa781000b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtCustomField1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='txtCustomField1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>3862b9b8-5178-4ec1-a930-98f06383fb4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e2d0fcfb-5ce8-4488-9f22-ebcc61ba9b41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtCustomField1</value>
      <webElementGuid>74431ec7-2efe-4eaa-ac6f-8c3378af2306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtCustomField1</value>
      <webElementGuid>971429bd-6085-4a11-a05a-6660f2ab5cc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-required</name>
      <type>Main</type>
      <value>customField.IsRequired</value>
      <webElementGuid>f8c4e2c8-97e3-4c93-b087-e517b1cc0d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lms-border lms-full-width lms-border-radius-10 lms-padding-10 lms-outline-0 lms-textarea-fixed-width ng-untouched ng-valid ng-valid-required ng-valid-pattern ng-valid-minlength ng-valid-maxlength ng-not-empty ng-dirty ng-valid-parse</value>
      <webElementGuid>d2b4b5a5-b942-4254-a5f1-ae2c4a24edb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>{'lms-disabled':customFieldListCtrl.disabled , 'border-error': ( customFieldListCtrl.customFieldForm.txtCustomField1.$invalid &amp;&amp; !customFieldListCtrl.customFieldForm.txtCustomField1.$pristine)
                            || (customFieldListCtrl.customFieldForm.txtCustomField1.$invalid &amp;&amp; submitted ) ,

                          'success': customFieldListCtrl.customFieldForm.txtCustomField1.$valid
                          &amp;&amp; customFieldListCtrl.customFieldForm.txtCustomField1.$touched &amp;&amp; !customFieldListCtrl.customFieldForm.txtCustomField1.$pristine }</value>
      <webElementGuid>38f8312c-6ce5-4072-8f92-6d26ea829489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>b0addc51-e3eb-41c3-a66b-8065eede33c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>customField.Value</value>
      <webElementGuid>5be6dbce-aa97-4b64-bd72-4c41d3418d4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-minlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>91cdcd1f-c1e3-43f6-9f0e-a004f2fe6417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4d2efe4a-1825-4b7c-8cd5-5ac5cfba3d72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>79af9e95-791b-4ead-ae05-08368f82f30c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c4d7e705-226e-4bf3-9c2c-581b8135aa05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-wsc-instance</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a12d7470-eee5-46e0-9845-88e0d9086154</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtCustomField1&quot;)</value>
      <webElementGuid>e2ab3e68-4a44-4c63-b64a-a4dd2a224986</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='txtCustomField1']</value>
      <webElementGuid>5a771067-b385-4f12-9e42-b0d7477011f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divAddEditUser']/div/div/form/div/fieldset/div/div/div[3]/div/div/div/div/div/custom-field-list/div/div/ng-form/div[2]/div/textarea</value>
      <webElementGuid>62e1ca52-6937-4150-8aa2-8bca3a9a2336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>b1197bd2-2451-4a2b-8f2d-fc871bdcc1ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@type = 'text' and @id = 'txtCustomField1' and @name = 'txtCustomField1']</value>
      <webElementGuid>807a49a1-83f1-4132-9236-d64a7ddd7fca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
