<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CreateUser_SelectSubject_DropDown</name>
   <tag></tag>
   <elementGuidId>be66924c-e40c-46f3-bcd3-dbc5cd0e1c4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-default.btn-block.dropdown-toggle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[6]/div/div/div[1]/div/div/div/div/form/div/fieldset/div/div/div[2]/div[2]/div[2]/custom-multiselect/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>49b8fa52-2a08-4a01-843d-4708fbd6b997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>31991d13-88ae-4fd8-8784-ab7917a48b85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default btn-block dropdown-toggle</value>
      <webElementGuid>509eadea-074c-44b4-b422-451f61b964d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>toggleDropdown()</value>
      <webElementGuid>95c4e7a4-cfbf-4e3c-8548-ee0c27d20881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>1a2b09ac-b4ea-48cf-93d0-4509ab65cff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        Select Value(s) 
    </value>
      <webElementGuid>7bdb38b6-2180-40c8-b083-bd29aff2be8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;multiSubjects&quot;)/div[@class=&quot;btn-group&quot;]/button[@class=&quot;btn btn-default btn-block dropdown-toggle&quot;]</value>
      <webElementGuid>9c13de1c-5f7f-43fc-8bba-12a8e9355c5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[13]</value>
      <webElementGuid>026a9567-1729-439c-a851-93bf89a45773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//custom-multiselect[@id='multiSubjects']/div/button</value>
      <webElementGuid>a354a3ad-a365-45c3-a06b-3b2050f0d713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subject'])[1]/following::button[1]</value>
      <webElementGuid>c982d87c-5cb8-4cc2-9b4a-53d595dd707d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::button[1]</value>
      <webElementGuid>6600066f-ddc8-4073-9280-7f86d64f8aff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//custom-multiselect/div/button</value>
      <webElementGuid>a8c07111-9529-4b14-bb94-94bc7b6e55a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
        Select Value(s) 
    ' or . = '
        Select Value(s) 
    ')]</value>
      <webElementGuid>93c67ee8-3212-4565-84ec-f15b86b980e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
