<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CreateUser_SetPassword_TextField</name>
   <tag></tag>
   <elementGuidId>7764172f-2790-4fd0-9c35-ea50b95a29c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-sm-5.lms-margin-start-28.lms-xs-only-margin-start-0-imp > input[name=&quot;setPassword&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='setPassword'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6033c96f-7dc7-4a33-8a5d-70b018addcbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-not-empty ng-dirty ng-valid-parse ng-valid ng-valid-required</value>
      <webElementGuid>84b5a02b-d5d7-434a-9e98-723e3c4134d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>setPassword</value>
      <webElementGuid>45968f19-d6eb-49dd-96c0-e1b9031735b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-disabled</name>
      <type>Main</type>
      <value>AddEditUserCtrl.resetPasswordBusy</value>
      <webElementGuid>1e206255-01f4-41ce-807e-5bb5489cf22a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>AddEditUserCtrl.user.password</value>
      <webElementGuid>1f25a16c-01e1-4701-b1a0-1a428e70f37a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value> Type Password</value>
      <webElementGuid>a6893dd8-978c-42a0-9db2-3f6219a7f09b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>a4169bd0-c1c4-4e6d-ab11-a94af41384bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>e50fdcf4-556c-4c84-9d76-c2d0d382f606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-blur</name>
      <type>Main</type>
      <value>AddEditUserCtrl.passwordPattern()</value>
      <webElementGuid>b4fb6c0f-abab-4653-8b6b-49487c9361e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>{'border-error': AddEditUserCtrl.userForm.setPassword.$invalid &amp;&amp; AddEditUserCtrl.userForm.setPassword.$error.required  &amp;&amp; (!AddEditUserCtrl.userForm.setPassword.$pristine  || submitted),'lms-border-error': AddEditUserCtrl.hidePatternMessage === false}</value>
      <webElementGuid>028c7f3a-b8e8-4768-90dd-0ab7d08d34f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6bd5eed9-4334-43f0-8119-26845f4dfe03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divPasswordSetting&quot;)/div[@class=&quot;row lms-margin-0&quot;]/div[@class=&quot;col-xs-12 lms-padding-top-2 lms-text-align-start lms-xs-only-padding-end-0-imp&quot;]/div[@class=&quot;col-sm-5 lms-margin-start-28 lms-xs-only-margin-start-0-imp&quot;]/input[@class=&quot;form-control ng-untouched ng-not-empty ng-dirty ng-valid-parse ng-valid ng-valid-required&quot;]</value>
      <webElementGuid>1fdbb23f-f544-44d5-936c-9ff0de0851a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='setPassword'])[2]</value>
      <webElementGuid>c21449da-0cc6-46c1-b9ea-7e543c8953ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divPasswordSetting']/div/div[3]/div/input</value>
      <webElementGuid>9d1f579b-cb4f-43d2-9a79-92f9692cfc11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>175dde17-765b-4906-b7db-14681903b780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'setPassword' and @placeholder = ' Type Password' and @type = 'password']</value>
      <webElementGuid>70eb4e19-be87-4094-84f8-57f2312ec100</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
