<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CreateUser_SelectTeacherRule_DropDown</name>
   <tag></tag>
   <elementGuidId>3b32cdfe-1abe-4e98-8cab-8d5cfc3b9bbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtUserRole</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='txtUserRole']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a76d37cc-2f0f-49fd-a297-ce7cde682104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>listview</value>
      <webElementGuid>f464b92d-094f-43ac-a7e7-0f0611f94cf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-valid ng-not-empty ng-valid-required ng-touched</value>
      <webElementGuid>ec3e295e-f62e-4aa1-8d4c-8c8d300b600b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtUserRole</value>
      <webElementGuid>b2f8229f-3918-48b7-89e2-6130309ee94d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Role</value>
      <webElementGuid>ea9c5c59-6f70-4ae3-a868-838baa8d4315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-disabled</name>
      <type>Main</type>
      <value>!($root.UserSchoolPermissions.indexOf('User.ChangeRole') > -1) &amp;&amp; AddEditUserCtrl.isInEditMode</value>
      <webElementGuid>bd42e51d-b045-48b5-8d01-077434242f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>AddEditUserCtrl.SelectedRoleId</value>
      <webElementGuid>eeb42eb1-c4ac-4c09-8f6f-263eb4e580b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-change</name>
      <type>Main</type>
      <value>AddEditUserCtrl.roleChanged(AddEditUserCtrl.SelectedRoleId)</value>
      <webElementGuid>5f294b40-1059-4a6d-868d-6dd9a8496938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>9b9ba0ad-dd7a-412b-947b-74f8cdd4d01b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-options</name>
      <type>Main</type>
      <value>option.RoleId as option.RoleName | optionsTrim:'20':'25':'50' | translate for option in AddEditUserCtrl.roles</value>
      <webElementGuid>9bb078d2-7dc3-432f-8993-07c33841fbba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>{'border-error': AddEditUserCtrl.userForm.Role.$invalid &amp;&amp; AddEditUserCtrl.userForm.Role.$error.required  &amp;&amp; (!AddEditUserCtrl.userForm.Role.$pristine || submitted)}</value>
      <webElementGuid>bdd8ce41-c3e5-4ef4-b1bb-f1d3f51c4f55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fa217f83-9a4e-4f4a-8e36-c0ecb0033b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> RoleTeacherStudentAcademic CoordinatorShadow TeacherHelp Teacherco adminGuest Studentacac newshadow tstudent 2ac testAdmin custom Oparent testSun risesun</value>
      <webElementGuid>e1598111-2f7c-4bd1-93a8-a72e5de742b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtUserRole&quot;)</value>
      <webElementGuid>f740aac5-fa4c-4288-a766-e15209adfe3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='txtUserRole']</value>
      <webElementGuid>1d4d9251-9695-4ef0-b187-962bff9d5ce4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divAddEditUser']/div/div/form/div/fieldset/div/div/div[2]/div/div/select</value>
      <webElementGuid>59806665-4329-4e72-8420-010e4c449baf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::select[1]</value>
      <webElementGuid>0c424599-8207-4360-9236-55b9688c9f3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subject'])[1]/preceding::select[1]</value>
      <webElementGuid>32cf6a17-3f06-4917-9e3d-4fa837ef5521</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/select</value>
      <webElementGuid>36436698-cfc9-4365-8fc8-cd0d80c5b9a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'txtUserRole' and @name = 'Role' and (text() = ' RoleTeacherStudentAcademic CoordinatorShadow TeacherHelp Teacherco adminGuest Studentacac newshadow tstudent 2ac testAdmin custom Oparent testSun risesun' or . = ' RoleTeacherStudentAcademic CoordinatorShadow TeacherHelp Teacherco adminGuest Studentacac newshadow tstudent 2ac testAdmin custom Oparent testSun risesun')]</value>
      <webElementGuid>d3270baa-6707-4c19-82c7-5665f59346e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
