<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Create__FirstName_TextField</name>
   <tag></tag>
   <elementGuidId>eb3f8599-ccaf-45d9-a7b6-28fbf2e2ed97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtFirstName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtFirstName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d2054b32-a3db-48ca-a316-ddcf6baadd0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4adab37d-2087-4eea-bd5c-ab51a0fa5acc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtFirstName</value>
      <webElementGuid>2f7e9233-9a2a-4b1a-bb0f-7dd45bf3bb5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-if</name>
      <type>Main</type>
      <value>!AddEditUserCtrl.addFirstNameTranslationEnabled</value>
      <webElementGuid>2e9c9556-51a6-4b06-a229-0ec32bd83ef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required ng-valid-minlength ng-valid-maxlength</value>
      <webElementGuid>632a57b0-46ad-4087-b008-5917112fc61d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>First Name</value>
      <webElementGuid>4cda5fa9-e9d5-4c1f-b9c9-1eb2f02ed807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FirstName</value>
      <webElementGuid>e8746dcc-800d-40e6-b914-260c42befb21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>AddEditUserCtrl.user.FirstName</value>
      <webElementGuid>a66bc0ea-5d37-4e5b-9ca9-dd51324ccc2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>03c20e2e-ca75-4f2c-8af4-7ea502107e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-minlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ee0d9bb9-3031-492a-8f69-e685e527d5ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>e94ac4ca-df03-49cf-9044-0031b335142a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>{'border-error': AddEditUserCtrl.userForm.FirstName.$invalid &amp;&amp; AddEditUserCtrl.userForm.FirstName.$error.required  &amp;&amp; (!AddEditUserCtrl.userForm.FirstName.$pristine || submitted)}</value>
      <webElementGuid>e545760b-ef08-429f-bd6e-5491283ecb78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>46197791-d7bc-4a7b-ae91-8be0d0ce9a5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtFirstName&quot;)</value>
      <webElementGuid>aa215ec1-fdc2-4aa8-bfe2-b9c4663e6fdf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtFirstName']</value>
      <webElementGuid>808701c5-f533-4131-9a18-f9d8ede6c5b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divAddEditUser']/div/div/form/div/fieldset/div/div/div/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>7c082e2a-3610-4b2a-84b7-402f9e0328d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>ea80f18f-e9e6-41a0-b3f6-11a9bdbfa9de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtFirstName' and @title = 'First Name' and @name = 'FirstName']</value>
      <webElementGuid>9e964393-01b0-4759-bd0e-7cb7a7951a58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
