<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CreateUser_ReEnterPassword_TextField</name>
   <tag></tag>
   <elementGuidId>25ff2b15-8c5d-4f25-aba8-8751db59a292</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;resetPassword&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='resetPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c859f8c7-1571-45b3-b9ed-a15d6c68134d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required</value>
      <webElementGuid>07e0a457-82fa-41e1-b9b6-04811ae0d7ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>resetPassword</value>
      <webElementGuid>4c616a5f-d419-472a-b3c0-8bf788e68d20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-disabled</name>
      <type>Main</type>
      <value>AddEditUserCtrl.resetPasswordBusy</value>
      <webElementGuid>611d6ecc-a8cf-4f84-a8cd-f3b7d5caa733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>AddEditUserCtrl.user.confirmPassword</value>
      <webElementGuid>2ae94e81-e5e9-4774-935c-b8d0ea1e1694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value> Retype Password</value>
      <webElementGuid>b192e15d-4bc8-4870-8e30-ad76390dbf48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>1ca01008-ec53-4cbe-a2ec-2f98b7d40b6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>3bfc06ce-85b9-4c84-bc0f-0d888b1dd60c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>{'border-error': AddEditUserCtrl.userForm.resetPassword.$invalid &amp;&amp; AddEditUserCtrl.userForm.resetPassword.$error.required  &amp;&amp; (!AddEditUserCtrl.userForm.resetPassword.$pristine || submitted),'lms-border-error': AddEditUserCtrl.user.confirmPassword &amp;&amp; (AddEditUserCtrl.user.confirmPassword !=AddEditUserCtrl.user.password)}</value>
      <webElementGuid>2be7b6a7-760a-4fae-82af-737159cb0acb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fbfe588d-b714-4393-89e2-03eb35f9e0e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divPasswordSetting&quot;)/div[@class=&quot;row lms-margin-0&quot;]/div[@class=&quot;col-xs-12 lms-padding-top-2 lms-text-align-start lms-xs-only-padding-end-0-imp&quot;]/div[@class=&quot;col-sm-5 lms-xs-only-margin-top-20&quot;]/input[@class=&quot;form-control ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required&quot;]</value>
      <webElementGuid>d7ea669f-87e6-4771-ad58-c634a9252854</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='resetPassword']</value>
      <webElementGuid>f283d489-012f-4468-a876-7776c80d8e5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divPasswordSetting']/div/div[3]/div[2]/input</value>
      <webElementGuid>ff8e2fb0-5d83-402a-abbf-a15ba9c5220d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>98d8750a-b48c-411a-a66f-a243030af6e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'resetPassword' and @placeholder = ' Retype Password' and @type = 'password']</value>
      <webElementGuid>750d7fd9-2532-45a1-a276-4e4a9140b530</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
