<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CreateUser_CloseSubjectDropDown_ArrowButton</name>
   <tag></tag>
   <elementGuidId>95177d17-4dff-4590-87ce-e6d8cff05b7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-default.btn-block.dropdown-toggle > span.caret</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//custom-multiselect[@id='multiSubjects']/div/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>58628259-a6e9-4928-a5e4-79a0dec9c9c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>caret</value>
      <webElementGuid>2e26d5b3-af35-4e76-92cb-3d72dbf3f600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;multiSubjects&quot;)/div[@class=&quot;btn-group&quot;]/button[@class=&quot;btn btn-default btn-block dropdown-toggle&quot;]/span[@class=&quot;caret&quot;]</value>
      <webElementGuid>9763db69-4544-46d7-a027-b9e16c60e4f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//custom-multiselect[@id='multiSubjects']/div/button/span</value>
      <webElementGuid>6d9e5a7f-e700-496f-8884-abe614a8d7fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//custom-multiselect/div/button/span</value>
      <webElementGuid>29fdce6f-9d81-430f-91be-72f5471f0253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//custom-multiselect[@id='multiSubjects']/div/ul/li[4]/a/span</value>
      <webElementGuid>f677db86-d826-479e-8270-7a6939620817</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//custom-multiselect/div/ul/li[4]/a/span</value>
      <webElementGuid>8414b681-5a09-4487-9cbc-bbfe48dd5c30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
