<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CreateUser_Save_Button</name>
   <tag></tag>
   <elementGuidId>a66201d4-5d8d-400d-a141-68b09c12d73e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnClosePopup</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnClosePopup']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>23a57148-f302-4af1-b61c-02f847b64ffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lms-transparent-bg lms-border-none lms-padding-end-5 lms-outline-0 text-muted</value>
      <webElementGuid>9480b71d-c086-4d12-92d9-2b3e1415b215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnClosePopup</value>
      <webElementGuid>d3c1bb62-ef88-4796-b4bf-87b68f74765a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dbd67c59-f86a-4871-8192-716de33d4764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-disabled</name>
      <type>Main</type>
      <value>AddEditUserCtrl.isInValid  || AddEditUserCtrl.customFieldForm.$invalid  || AddEditUserCtrl.userForm.$invalid || AddEditUserCtrl.customFieldFormAdd.$invalid</value>
      <webElementGuid>c05e8374-86d1-45c2-b304-22855ee48e18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>AddEditUserCtrl.saveUser()</value>
      <webElementGuid>65d66815-eb3a-4c44-ad68-849680a073f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>{'text-muted':!AddEditUserCtrl.isInEditMode,'lms-color-lnks':AddEditUserCtrl.isInEditMode,'lms-disabled': AddEditUserCtrl.isInValid  || AddEditUserCtrl.customFieldForm.$invalid  || AddEditUserCtrl.userForm.$invalid || AddEditUserCtrl.customFieldFormAdd.$invalid}</value>
      <webElementGuid>aa425649-ea0c-44f8-a6ff-6744835e76e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                     Save
                                </value>
      <webElementGuid>0eaddbc5-2897-4167-87d6-e6cbac6fd6c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnClosePopup&quot;)</value>
      <webElementGuid>5b53580e-8c1e-4ab8-bf36-3eacae2e67b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnClosePopup']</value>
      <webElementGuid>90b74b52-8fd4-48ce-a599-bc9ada04c499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divAddEditUser']/div/div/form/div/fieldset/div/div/footer/div/button</value>
      <webElementGuid>c42b60d3-debf-4244-845f-07d565bf1ba9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Initiate Calendar'])[3]/following::button[1]</value>
      <webElementGuid>02c52106-36bf-4e94-9cba-88b110b07bac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::button[1]</value>
      <webElementGuid>da0bda5b-f928-42b9-8702-3223f118cd52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>1511b045-5a9a-4564-bba5-0ffe88725422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/button</value>
      <webElementGuid>cf785ca2-e312-451f-8d69-03e36e2bcb61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnClosePopup' and @type = 'button' and (text() = '
                                     Save
                                ' or . = '
                                     Save
                                ')]</value>
      <webElementGuid>304d24f6-1635-4521-b87b-d10b0727b7ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
