<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DotSelect_CreatePassword_Select</name>
   <tag></tag>
   <elementGuidId>b5a67d8c-e84b-4573-abdd-34855ed180bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>em.fa-lg.fa-fw.fal.fa-tools</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[6]/div/div/div[1]/div/div/div/div/form/div/fieldset/div/div/div[1]/div/div/div[2]/div[3]/div[2]/div/div[2]/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
      <webElementGuid>3be8accf-5c1b-41cb-b364-9d373b7be5d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;left-panel&quot;)/div[@class=&quot;lms-left-panel-bg&quot;]/nav[@class=&quot;lms-left-nav lms-padding-bottom-10&quot;]/ul[@class=&quot;lms-user-profile lms-animate-ul-text lms-loading-ico&quot;]/li[@class=&quot;lms-menu-group-link active lms-icon-visible&quot;]/a[@class=&quot;lms-cursor-pointer lms-nowrap&quot;]/em[@class=&quot;fa-lg fa-fw fal fa-tools&quot;]</value>
      <webElementGuid>ab1ce1a1-6dbf-4c77-aaec-39838e3c05e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa-lg fa-fw fal fa-tools</value>
      <webElementGuid>10ffc28b-66d5-4549-85fe-2cae075abb67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//aside[@id='left-panel']/div/nav/ul/li[4]/a/em</value>
      <webElementGuid>a48b2de1-36bb-4094-a086-6776a8a6a331</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a/em</value>
      <webElementGuid>83812ef7-4fbd-4f72-9260-2cf68b2a32ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divPasswordSetting']/div/div[2]/label/em</value>
      <webElementGuid>37398558-8911-4ea6-8412-5d14d9f936f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label/em</value>
      <webElementGuid>db43b242-b890-4108-b45e-ddadb2154a1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
