<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EditUser_NewSchool_DropDown</name>
   <tag></tag>
   <elementGuidId>65e72716-0713-4f89-88f1-f9dd37d56568</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>em.fa.fa-caret-down.lms-verical-middle.lms-float-end.lms-margin-top-10</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='lblSegments1']/em</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
      <webElementGuid>5348bf5a-fed2-4955-b0b1-6825b8ee407b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-caret-down lms-verical-middle lms-float-end lms-margin-top-10</value>
      <webElementGuid>336358c6-6c7c-4859-8a04-b4fde59f7c5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f656442b-43c5-4c9f-8e3e-82bb88591b49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lblSegments1&quot;)/em[@class=&quot;fa fa-caret-down lms-verical-middle lms-float-end lms-margin-top-10&quot;]</value>
      <webElementGuid>d1b0a106-efc7-41c9-8ed3-5d56be190e7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='lblSegments1']/em</value>
      <webElementGuid>4b4a0857-8708-49a2-810c-41c9a54a8690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/a/em</value>
      <webElementGuid>89ff872b-4e17-4125-9b53-a46fff15de04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
