<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EditUser_SaveAllUserInformation_Button</name>
   <tag></tag>
   <elementGuidId>d9e0b2cf-e3a6-45ae-8133-a297743bf314</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-xs-12.lms-text-align-end.lms-padding-0 > #btnClosePopup</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='btnClosePopup'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e436e711-cc66-4e26-a958-dafd398418a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary lms-height-unset  lms-edit-mode-btn</value>
      <webElementGuid>ad8fbf2e-1b6a-4c05-aecc-fc16e9711771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnClosePopup</value>
      <webElementGuid>d3ce108f-4eed-4cff-a08c-76c55367b9b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-disabled</name>
      <type>Main</type>
      <value>!AddEditUserCtrl.enableSaveMultirole &amp;&amp; !AddEditUserCtrl.managerTabCahnged</value>
      <webElementGuid>02c94f77-2a1d-4c5f-8a18-2a886ad3ce73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>77d71ede-04b1-4358-81da-4e699b2b3fcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>{'lms-edit-mode-btn':AddEditUserCtrl.isInEditMode}</value>
      <webElementGuid>14060fa8-0e3c-4fba-93eb-2305c0aa18a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>AddEditUserCtrl.saveNewUser()</value>
      <webElementGuid>0687d714-8941-4257-9e98-0ce9c15bc3aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                 Save
            </value>
      <webElementGuid>aafbb018-3f5f-4ed0-8c45-335d2abb44fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;font-s--1 lms-font-montserrat-regular js flexbox flexboxlegacy canvas canvastext webgl no-touch geolocation postmessage no-websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers no-applicationcache svg inlinesvg smil svgclippaths js flexbox flexboxlegacy canvas canvastext webgl no-touch geolocation postmessage no-websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers no-applicationcache svg inlinesvg smil svgclippaths web-font&quot;]/body[@class=&quot;minified smart-ltr desktop-detected scrolled modal-open&quot;]/div[@class=&quot;modal fade in&quot;]/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;lms-row lms-clear&quot;]/footer[@class=&quot;lms-row lms-clear lms-margin-top-20 modal-footer&quot;]/div[@class=&quot;col-xs-12  lms-text-align-end  lms-padding-0&quot;]/button[@id=&quot;btnClosePopup&quot;]</value>
      <webElementGuid>1c27a9d3-c2d8-4fde-b00c-69b07e96c870</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='btnClosePopup'])[2]</value>
      <webElementGuid>66d791f1-59dc-462f-a171-ed08a00a840b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::button[1]</value>
      <webElementGuid>47845c2e-7a63-44b5-b69d-aa532d2acb3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[2]</value>
      <webElementGuid>4a3fbdde-a04e-4913-904e-4c424731a031</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/preceding::button[1]</value>
      <webElementGuid>6884bd55-216c-4492-905f-d216d854b476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/button</value>
      <webElementGuid>73c61ba4-a81e-4590-ad2b-5701983892b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnClosePopup' and @type = 'button' and (text() = '
                 Save
            ' or . = '
                 Save
            ')]</value>
      <webElementGuid>030ee6ba-0b4e-4309-92aa-441e8a7fd9ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
