<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EditUser_SaveNewInformation_Button</name>
   <tag></tag>
   <elementGuidId>9daa2b4e-abb0-405e-b7ad-c34428b4c1af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnDoneUserRole</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnDoneUserRole']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e9d0f9af-8023-49ae-9100-2ed35915fbed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5bce7176-09cc-4e4b-9838-c2e96a711323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnDoneUserRole</value>
      <webElementGuid>98df1560-2130-411e-bf66-8560fd714cf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn text-muted  btn-link lms-solid-border-end lms-xs-padding-start-0 lms-xs-only-text-start color-lnks</value>
      <webElementGuid>15365caa-4193-4dac-bb1c-0e8c5f655698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value> Save</value>
      <webElementGuid>8b800f59-2353-4b36-9ef4-6bef99c257fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>AddEditUserCtrl.doneNewUserRole($index)</value>
      <webElementGuid>678c15b7-91b9-4bfe-ac1a-719ba0dbda05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-disabled</name>
      <type>Main</type>
      <value>userRole.SelectedRoleId == undefined ||  userRole.SelectedRoleId == null || !AddEditUserCtrl.isAvailableRole(userRole.SelectedRoleId) || userRole.roleError || !AddEditUserCtrl.userForm.$valid</value>
      <webElementGuid>abb136d0-800f-4a40-9c06-9e31a64a62e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>{'color-lnks': !(userRole.SelectedRoleId == undefined ||  userRole.SelectedRoleId == null || userRole.roleError || !AddEditUserCtrl.userForm.$valid)}</value>
      <webElementGuid>4347afba-c6bd-4e60-a328-da992004b4d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                             Save
                                        </value>
      <webElementGuid>a1a7c6c1-b2a5-43bc-9964-89ceb616afab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnDoneUserRole&quot;)</value>
      <webElementGuid>500fd210-c099-4ae6-b15c-b1ad468ce1a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnDoneUserRole']</value>
      <webElementGuid>0db44e42-a10d-40e3-9336-c6645bfa25cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='liUserMultiRoles1']/div/div/div[3]/button</value>
      <webElementGuid>eef3693c-4600-41e3-9462-55d18ab1cc0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='zzzzzzzzzzzz'])[1]/following::button[1]</value>
      <webElementGuid>7fbce1db-5321-4965-8c89-cd37f9ff2c19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vocational Studies'])[1]/following::button[1]</value>
      <webElementGuid>0ecda162-1c48-47b1-9e8f-f333fb3947ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::button[1]</value>
      <webElementGuid>66096983-b2ad-4591-ad71-faa912be31d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/preceding::button[2]</value>
      <webElementGuid>6d99ab53-2b23-4bae-8432-333aeaa4eb41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>511795b0-14e5-4e74-ad09-93dab9250651</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/div[3]/button</value>
      <webElementGuid>580e78d4-279c-4455-b644-472bc52ea45e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnDoneUserRole' and @title = ' Save' and (text() = '
                                             Save
                                        ' or . = '
                                             Save
                                        ')]</value>
      <webElementGuid>d7a8e5cb-5365-4d79-8b1d-d3a93b0a4199</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
