<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EditUser_ChooseNewSchool_FromDropDown</name>
   <tag></tag>
   <elementGuidId>048a88d8-9e36-4a43-a962-05f40eee064f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#org-tree1 > li.angular-ui-tree-node > div.lms-angluar-ui-tree.angular-ui-tree-handle > #school_94ba5777-f176-43d7-844d-229f9789ba53</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//span[@id='school_94ba5777-f176-43d7-844d-229f9789ba53'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8277c955-f1f2-461d-ac77-ab560afc5c86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>school_94ba5777-f176-43d7-844d-229f9789ba53</value>
      <webElementGuid>79bc66c5-d6ae-4dcf-aa52-80498bb34a50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>0d573624-c8a5-4590-8115-dab81d84e024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>{'lms-tree-selected': node.SchoolId == AddEditUserCtrl.selectedSchoolId}</value>
      <webElementGuid>8df986ee-dd31-48f7-a98c-b08946aecde3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>AddEditUserCtrl.selectSchoolNode(node,userRole)</value>
      <webElementGuid>1f01ffb7-9e01-4cef-a158-1da68cc3afb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lms-tree-name lms-tree-name0 lms-tree-selected</value>
      <webElementGuid>03f89319-4e42-4052-a732-90c0f2d45db3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Parent School</value>
      <webElementGuid>b3518d27-2e07-4e00-954f-f09c876fdaf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3ebd0fed-73bd-4d79-88c5-6f85f907ee51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3408a02f-c218-44b3-8f4a-2d4cc3746ef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Parent School</value>
      <webElementGuid>31d1933a-0d30-4592-b63c-55115eb47a2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;org-tree1&quot;)/li[@class=&quot;angular-ui-tree-node&quot;]/div[@class=&quot;lms-angluar-ui-tree angular-ui-tree-handle&quot;]/span[@id=&quot;school_94ba5777-f176-43d7-844d-229f9789ba53&quot;]</value>
      <webElementGuid>50d0a919-d584-4837-81f9-193d2a6d424b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//span[@id='school_94ba5777-f176-43d7-844d-229f9789ba53'])[2]</value>
      <webElementGuid>8367ff03-8544-45fd-a1ba-2ee8f1ad4f40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ol[@id='org-tree1']/li/div/span</value>
      <webElementGuid>663431fe-91ed-4a31-bcc2-1a0f56c53819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organization'])[4]/following::span[2]</value>
      <webElementGuid>c914c20f-853a-4366-ad3a-d679e09e3d63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select School Name'])[1]/following::span[4]</value>
      <webElementGuid>5167c6fb-f9f7-4218-9af1-bbe1b0e5e847</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Primary School'])[4]/preceding::span[1]</value>
      <webElementGuid>32bcde6e-454c-4b88-8aa9-59650f847c93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Second school'])[2]/preceding::span[7]</value>
      <webElementGuid>ba86fdc8-b358-40be-81d5-6b8d652aa17c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ol/li/div/span</value>
      <webElementGuid>5bd613a1-07b8-4ace-8ebe-bd6fa7a81fc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'school_94ba5777-f176-43d7-844d-229f9789ba53' and @title = 'Parent School' and (text() = 'Parent School' or . = 'Parent School')]</value>
      <webElementGuid>f470c057-5d2e-48d1-83c6-428a84d6a2df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
