<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EditUser_SelectNewRole_DropDown</name>
   <tag></tag>
   <elementGuidId>c19ce2a5-fa02-4832-ad7f-6a13022ad9ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtUserRole1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='txtUserRole1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>12fe9b44-f802-4ad4-8a97-6ad8d0c1758c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>listview</value>
      <webElementGuid>2017cc99-3991-4c42-af8b-7c9d74fba652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required</value>
      <webElementGuid>0538dc5c-94ed-498f-bcb2-84861c0afe9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtUserRole1</value>
      <webElementGuid>d8a2453a-03c0-4d80-8924-8e9896ad7710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Role[$index]</value>
      <webElementGuid>fe0ccfb7-fcdd-45f0-b82a-b50ed5262a6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>userRole.SelectedRoleId</value>
      <webElementGuid>bd520cb2-3bab-4e59-b813-1c727d5f0829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-change</name>
      <type>Main</type>
      <value>AddEditUserCtrl.EdRoleChanged(userRole.SelectedRoleId,$index)</value>
      <webElementGuid>4b854b57-0808-48b9-8a84-423e9a462556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>e202e003-ea6a-44cb-bf44-30eefea9cac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-options</name>
      <type>Main</type>
      <value>option.RoleId as option.RoleName | optionsTrim:'20':'25':'40' | translate for option in userRole.EDModeRoles</value>
      <webElementGuid>9d4fa5f2-085c-4a63-ab7a-7a41f2313a6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>{'border-error': AddEditUserCtrl.userForm.Role[$index].$invalid &amp;&amp; AddEditUserCtrl.userForm.Role[$index].$error.required  &amp;&amp; (!AddEditUserCtrl.userForm.Role[$index].$pristine)}</value>
      <webElementGuid>f4acafea-e19e-4154-91ff-57860f8e6ddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dfe3ef73-42d6-4f2d-8a75-8cc7f0e636c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> RoleTeacherStudentParentAcademic CoordinatorShadow TeacherHelp Teacherco adminGuest Studentacac newshadow tstudent 2ac testAdmin custom Oparent testSun risesun</value>
      <webElementGuid>34aac74c-fb91-48d8-9987-aa46284d792f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtUserRole1&quot;)</value>
      <webElementGuid>8992b4fb-fcf1-4257-9eda-6c2353457d40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='txtUserRole1']</value>
      <webElementGuid>175bf6ae-09dd-4142-bf74-3610b3b4eb82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='liUserMultiRoles1']/div/div/div/div[2]/div/select</value>
      <webElementGuid>735df6f1-283c-4410-af6f-4b854395fd94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role'])[2]/following::select[1]</value>
      <webElementGuid>c19c336a-e02a-431d-a1b9-7d84451f2158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='esraa subschool'])[2]/following::select[1]</value>
      <webElementGuid>c65472d9-6791-48a4-96b7-c8323d0ce0c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::select[1]</value>
      <webElementGuid>51144a6f-1587-4bcb-aa17-226f8a6150fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::select[1]</value>
      <webElementGuid>7b04e215-7a9a-4a17-b3a9-5fe0929f4f01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/div/div[2]/div/select</value>
      <webElementGuid>5b56c131-c766-4a9b-bf14-2e3f7b1db2c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'txtUserRole1' and @name = 'Role[$index]' and (text() = ' RoleTeacherStudentParentAcademic CoordinatorShadow TeacherHelp Teacherco adminGuest Studentacac newshadow tstudent 2ac testAdmin custom Oparent testSun risesun' or . = ' RoleTeacherStudentParentAcademic CoordinatorShadow TeacherHelp Teacherco adminGuest Studentacac newshadow tstudent 2ac testAdmin custom Oparent testSun risesun')]</value>
      <webElementGuid>10291f18-def4-48c0-b379-b24a3f254fbc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
