<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ParentSchool_Tab_Select</name>
   <tag></tag>
   <elementGuidId>c42a2ad6-1c24-4c30-ad84-b8e17245da8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#school_94ba5777-f176-43d7-844d-229f9789ba53</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='school_94ba5777-f176-43d7-844d-229f9789ba53']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8a278b32-8225-41ec-88dc-dd414476656a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>8e035345-d437-4f32-9b76-46d813ae19cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>school_94ba5777-f176-43d7-844d-229f9789ba53</value>
      <webElementGuid>ef6db7d4-1c09-444c-ab0f-afa5e4843cc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>vm.selectSchoolNode(node,$event)</value>
      <webElementGuid>90e63c92-c27b-48b4-9a3c-a22decfe3435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>{'lms-tree-selected': node.SchoolId == vm.currentSelectedSchool.SchoolId}</value>
      <webElementGuid>df83253b-d92d-4e17-ad7c-745cf42df910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lms-tree-name</value>
      <webElementGuid>bc2b508a-ebe2-4cb9-9d82-66756772128e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Parent School</value>
      <webElementGuid>20934812-eb36-49e3-aee6-f6aea54566fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>025639b3-15ea-469b-8387-d6734bc10c63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3f57bcdf-380c-4a9a-b4d4-46197c336839</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Parent School
        </value>
      <webElementGuid>80817acd-9f78-4d13-b7cc-276f6152bb81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;school_94ba5777-f176-43d7-844d-229f9789ba53&quot;)</value>
      <webElementGuid>eb813fe3-3978-4498-b396-2dde51ec6bc9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='school_94ba5777-f176-43d7-844d-229f9789ba53']</value>
      <webElementGuid>8c6f5302-2148-4642-a44b-d7c36a60dd2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='liEle0']/div/span</value>
      <webElementGuid>68ec721a-ede4-4201-9dc8-fad6c5711ee9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organization'])[3]/following::span[2]</value>
      <webElementGuid>c72ae4b2-e374-4c58-9a21-69db4173a6e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Include people in schools and sub schools'])[1]/following::span[3]</value>
      <webElementGuid>a66b7f9d-41a1-4e9b-9382-691c0c0424e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Primary School'])[3]/preceding::span[1]</value>
      <webElementGuid>e6ba16ba-2a56-4c14-b150-04f086f97371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Second school'])[1]/preceding::span[7]</value>
      <webElementGuid>a86cc6e0-c581-4923-af4f-256fa1649f12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Parent School']/parent::*</value>
      <webElementGuid>7298c76f-f98a-4a4e-94e6-3da298424429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol/li/div/span</value>
      <webElementGuid>e96f3867-5897-4115-9915-3fc75c184cf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'school_94ba5777-f176-43d7-844d-229f9789ba53' and @title = 'Parent School' and (text() = '
            Parent School
        ' or . = '
            Parent School
        ')]</value>
      <webElementGuid>1a122b35-c28c-4882-b6ed-e8f9291dde2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
