<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RoleIndexing</name>
   <tag></tag>
   <elementGuidId>eea80cf2-bbf5-481e-81f6-8c0a0c2617ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtUserRole1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='txtUserRole1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b874535d-56f9-42ef-be15-7a6fe4a9bd3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>listview</value>
      <webElementGuid>9e4dcf59-b30c-467f-8c4a-7a9df09d0af1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required</value>
      <webElementGuid>ea07a51f-b578-4b5f-9f27-013e30b114eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtUserRole1</value>
      <webElementGuid>f54cce66-7b3e-4533-92bd-29e962ff33c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Role[$index]</value>
      <webElementGuid>6eaa7315-4b97-4957-bea5-637f990be3e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>userRole.SelectedRoleId</value>
      <webElementGuid>7c3c2c1a-e8b5-4421-812b-7bc2e0dace87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-change</name>
      <type>Main</type>
      <value>AddEditUserCtrl.EdRoleChanged(userRole.SelectedRoleId,$index)</value>
      <webElementGuid>f31fd631-310d-431a-9ec4-b55afbac67c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>c09a1851-5254-4128-a719-95b4ff9d1f21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-options</name>
      <type>Main</type>
      <value>option.RoleId as option.RoleName | optionsTrim:'20':'25':'40' | translate for option in userRole.EDModeRoles</value>
      <webElementGuid>4240fa2b-8ec1-42d0-acab-4d0c1e348837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>{'border-error': AddEditUserCtrl.userForm.Role[$index].$invalid &amp;&amp; AddEditUserCtrl.userForm.Role[$index].$error.required  &amp;&amp; (!AddEditUserCtrl.userForm.Role[$index].$pristine)}</value>
      <webElementGuid>3e2ef0fd-bdc1-4675-b492-e80973e97112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>de99a6e3-2bb6-4d7e-ba26-b6e3628e51b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> RoleTeacherStudentParentAcademic CoordinatorShadow TeacherHelp Teacherco adminGuest Studentacac newshadow tstudent 2ac testAdmin custom Oparent testSun risesun</value>
      <webElementGuid>be2abade-97f1-42f3-bdde-e115bdb47261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtUserRole1&quot;)</value>
      <webElementGuid>32f249d0-9f67-49e3-943a-c0eae691f99d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='txtUserRole1']</value>
      <webElementGuid>b0a72e1e-dc79-4579-b97d-c570254ca7b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='liUserMultiRoles1']/div/div/div/div[2]/div/select</value>
      <webElementGuid>f9abc3e7-b2a7-413d-98eb-c59821ffea3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role'])[2]/following::select[1]</value>
      <webElementGuid>3307eb43-0fff-4e72-918b-2f35c15a6713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='esraa subschool'])[2]/following::select[1]</value>
      <webElementGuid>5c4b1b24-1bc1-45c4-9c14-6f120bc93e33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::select[1]</value>
      <webElementGuid>8c226229-5ec6-4bbc-9786-ab216731e7ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::select[1]</value>
      <webElementGuid>46e9f7fa-94c6-47bf-aa2e-d47fa130233d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/div/div[2]/div/select</value>
      <webElementGuid>7879e8ce-fcaa-4c2e-9575-7944b92fabd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'txtUserRole1' and @name = 'Role[$index]' and (text() = ' RoleTeacherStudentParentAcademic CoordinatorShadow TeacherHelp Teacherco adminGuest Studentacac newshadow tstudent 2ac testAdmin custom Oparent testSun risesun' or . = ' RoleTeacherStudentParentAcademic CoordinatorShadow TeacherHelp Teacherco adminGuest Studentacac newshadow tstudent 2ac testAdmin custom Oparent testSun risesun')]</value>
      <webElementGuid>6af9515b-f1d3-4072-b51a-0fec6caee9e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
