<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SearchUser_SearchField</name>
   <tag></tag>
   <elementGuidId>27f98279-231f-4869-9248-026cfa24d19f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtsearchUser</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtsearchUser']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>558666fe-10cd-4a95-9a18-53eddbd15062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>vm.searchUserName</value>
      <webElementGuid>e94e647b-98c1-4982-9423-79ab5c1e7039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fc639aeb-fc3e-4e7d-ac0f-102dcda1cedf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Search By Name or Email</value>
      <webElementGuid>f2cee987-0ccf-4a1f-ad99-fbd7ce2219a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>searchUser</value>
      <webElementGuid>b3b3d0a6-b887-49a0-a982-bc1d8625bb2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtsearchUser</value>
      <webElementGuid>1d82e69c-86a7-4ab9-99be-d91d7f46b20c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>d28da760-5c11-49fb-9f9c-1ac5d87dcf29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-minlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2b4d9cc7-616a-4797-9953-bcfca682d3fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search By Name or Email</value>
      <webElementGuid>367c3814-40ac-4398-9472-f114439ee055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lms-border-none form-control ng-pristine ng-empty ng-invalid ng-invalid-required ng-valid-minlength ng-valid-maxlength ng-touched</value>
      <webElementGuid>d717fcb8-f66d-410b-88ee-eb214fcd7f6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-maxlength</name>
      <type>Main</type>
      <value>199</value>
      <webElementGuid>973320ce-60a6-4c6d-a5a8-45babc8a99ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-keypress</name>
      <type>Main</type>
      <value>vm.handelSearchUserEnter($event)</value>
      <webElementGuid>05477bec-68a6-479d-9cee-d42ad5da0fe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b5874087-a7ab-40b2-90a4-d526d7d86c9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtsearchUser&quot;)</value>
      <webElementGuid>525aadf1-e598-4afe-9876-f7ab1fc46276</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtsearchUser']</value>
      <webElementGuid>6fd35c00-23e8-497d-bde7-5ec30c3ca081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='office365Div']/div/div/div/div/div/div[3]/div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>5ab6f91b-75da-496e-9271-0536ece89332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>9310df63-7eeb-4520-b034-40ec6bfb2a08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @title = 'Search By Name or Email' and @name = 'searchUser' and @id = 'txtsearchUser' and @placeholder = 'Search By Name or Email']</value>
      <webElementGuid>32c13c4c-8abe-4bff-9787-0958da3373c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
