<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SearchTab_Button</name>
   <tag></tag>
   <elementGuidId>fdd860dd-f95a-4f49-9589-314b48b77653</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnUserOrganSearch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnUserOrganSearch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cf853299-5590-4b38-a682-ac868dcfd6bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnUserOrganSearch</value>
      <webElementGuid>dc604f9f-9a8c-433a-a023-651886039274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-disabled</name>
      <type>Main</type>
      <value>!vm.searchUserName || vm.searchUserName.length &lt; 3</value>
      <webElementGuid>b656e5d8-20d8-4ad9-806f-fb4d38e6282f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>vm.searchForUser()</value>
      <webElementGuid>c0d0aafb-9522-45d7-8ab8-ce7c9d2125cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-xs-12 lms-padding-start-0 lms-padding-end-0 btn btn-link </value>
      <webElementGuid>9d2c5143-1f8f-4873-a7bc-6149ad527f6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Search By Name or Email</value>
      <webElementGuid>9af23cac-1409-47f2-b3ea-f4c77590019f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>325e1a39-6426-43bc-bdff-7ac83a4baa4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                        
                                        search
                                    </value>
      <webElementGuid>22d193a2-0c09-4f5d-850a-a2bca2f3700c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnUserOrganSearch&quot;)</value>
      <webElementGuid>dadb31a5-18c5-4356-bac1-2b158eb29693</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnUserOrganSearch']</value>
      <webElementGuid>8df3d961-54bc-4a6b-a475-bcb4284e0c0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='office365Div']/div/div/div/div/div/div[3]/div[2]/div[2]/div/div/div/div[2]/button</value>
      <webElementGuid>288edcf9-2b5d-42fe-b376-e27a24f0c206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Users'])[1]/following::button[1]</value>
      <webElementGuid>be873a75-5dbc-41ba-b56f-a764c30d5b73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='search'])[2]/preceding::button[1]</value>
      <webElementGuid>507b094c-e8d2-4954-8d54-ccf5f15aaa69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/button</value>
      <webElementGuid>965e8159-da3b-4d9a-a9a2-f17502656553</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnUserOrganSearch' and @title = 'Search By Name or Email' and @type = 'submit' and (text() = '
                                        
                                        search
                                    ' or . = '
                                        
                                        search
                                    ')]</value>
      <webElementGuid>8a8e3037-81a9-4a97-a8f7-755a680f03bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
