<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Search_Button</name>
   <tag></tag>
   <elementGuidId>3c79634e-2a63-429b-bcfa-2b5f34dacd89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>em.fa.fa-search.lms-font-medium</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnUserOrganSearch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
      <webElementGuid>6a073b66-daf1-4268-9967-54ed3315a939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-search lms-font-medium</value>
      <webElementGuid>bbbf1bcf-69f1-4857-be76-2052f077ad10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnUserOrganSearch&quot;)/em[@class=&quot;fa fa-search lms-font-medium&quot;]</value>
      <webElementGuid>fa5e0d2e-b0c2-4dad-b2fe-161354909c9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='btnUserOrganSearch']/em</value>
      <webElementGuid>b9b7046e-1550-41d1-8e82-d674424e6d39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/em</value>
      <webElementGuid>67d0380b-5931-4039-b944-6c5c436d78f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
