<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SelectTeacherRole_DropDown</name>
   <tag></tag>
   <elementGuidId>4c922803-eb2d-4b0a-9c57-19e404872dfd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SelectFilterRoles</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='SelectFilterRoles']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6968d64c-edda-4ffe-9425-1b7b3d6bddc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SelectFilterRoles</value>
      <webElementGuid>2129b6c2-cb93-4de5-93de-26a8841e238f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SelectFilterRoles</value>
      <webElementGuid>8798561a-02db-4f9b-bfe5-cda44450e286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-valid ng-empty</value>
      <webElementGuid>6c4997cd-cbad-41c9-aba4-7c45ef4a8998</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>vm.filterRoleModel</value>
      <webElementGuid>83ab3081-16de-4a87-a093-eb688615f5cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-options</name>
      <type>Main</type>
      <value>item as item.RoleName | optionsTrim for item in vm.roles track by item.RoleId</value>
      <webElementGuid>52a476b9-23da-477f-a04d-ac763ed8b8f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-change</name>
      <type>Main</type>
      <value>vm.loadGrades();vm.searchForUser()</value>
      <webElementGuid>a043644a-61a5-4477-bc31-e10fbd2b0dc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7a0d49e3-989c-4bde-9d8e-c584fbe724f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select RoleTeacherStudentAdminParentAcademic CoordinatorShadow TeacherHelp Teacherco adminGuest Studentacac newshadow tstudent 2cu admincustom admin 333ac testAdmin custom Oparent testSun risesun</value>
      <webElementGuid>49bc4cc1-6d3e-4d3a-ba57-2d92cf88873a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SelectFilterRoles&quot;)</value>
      <webElementGuid>acb60cac-8a46-4911-b6f2-927a842473f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='SelectFilterRoles']</value>
      <webElementGuid>8ac6982c-190f-44b7-893d-ac503caa492d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='office365Div']/div/div/div/div/div/div[3]/div[2]/div[2]/div[2]/div/select</value>
      <webElementGuid>d18b5976-9bd5-4558-a398-3f3ea04ec2a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='search'])[1]/following::select[2]</value>
      <webElementGuid>77e9911b-2030-4531-9e45-53aa984147de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='search'])[2]/preceding::select[2]</value>
      <webElementGuid>f786b015-a1da-405d-b97d-2e0b3fcabeae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Name'])[1]/preceding::select[2]</value>
      <webElementGuid>bcf0335b-3869-4f14-936e-f4906ecd78a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>ec996db1-1842-4beb-bd16-0f27ebe20867</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'SelectFilterRoles' and @name = 'SelectFilterRoles' and (text() = 'Select RoleTeacherStudentAdminParentAcademic CoordinatorShadow TeacherHelp Teacherco adminGuest Studentacac newshadow tstudent 2cu admincustom admin 333ac testAdmin custom Oparent testSun risesun' or . = 'Select RoleTeacherStudentAdminParentAcademic CoordinatorShadow TeacherHelp Teacherco adminGuest Studentacac newshadow tstudent 2cu admincustom admin 333ac testAdmin custom Oparent testSun risesun')]</value>
      <webElementGuid>a6f91f2f-ee90-473f-97b0-28e33ead621b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
