<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_Language_DropDown</name>
   <tag></tag>
   <elementGuidId>b2c683f7-331a-4d96-a50b-da11883eddf6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtLanguage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='txtLanguage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>41e0ebc6-ff4a-49e2-a6ea-e2d8c451e31a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>listview</value>
      <webElementGuid>eed4e644-6613-47f4-ac6e-41a89b657ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required</value>
      <webElementGuid>00d9eb5d-3513-47ba-bc17-b50b1e219797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>468ff1a1-7e5a-4483-9897-19ddbe5af224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Language</value>
      <webElementGuid>04ec8df4-c41e-4a9b-b097-57a7554902f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtLanguage</value>
      <webElementGuid>dc80fac9-d856-43aa-94ec-1f1c221f96fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>AddEditUserCtrl.user.Language</value>
      <webElementGuid>47e49c20-1ec4-48b6-a0f0-7902283b9ac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-options</name>
      <type>Main</type>
      <value>option.UrlPath as option.DisplayName for option in AddEditUserCtrl.availableLanguages</value>
      <webElementGuid>9b1cdb07-70c0-4219-ab25-9dea68a7375a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>{'border-error':AddEditUserCtrl.userForm.Language.$invalid &amp;&amp; AddEditUserCtrl.userForm.Language.$error.required  &amp;&amp; (!AddEditUserCtrl.userForm.Language.$pristine || submitted)}</value>
      <webElementGuid>46897758-2015-45b2-8d18-99a8799d283b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bbb362c0-b8d2-42c4-8d35-33603333598b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LanguageEnglishالعربيةEspañolFrançaisPortuguês</value>
      <webElementGuid>38881fa8-33b6-466b-b8ca-ca6c7a771b2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtLanguage&quot;)</value>
      <webElementGuid>f3a702d9-4728-4fc8-86db-cb90d9452023</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='txtLanguage']</value>
      <webElementGuid>4919532d-8361-4772-b3d5-86d83fe7f4f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divAddEditUser']/div/div/form/div/fieldset/div/div/div/div/div/div[2]/div[2]/div/div/select</value>
      <webElementGuid>4f00f962-3c5c-43f4-bc2b-57babcf38e93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::select[1]</value>
      <webElementGuid>83f1c641-9141-47f9-9803-2c280ac69768</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/preceding::select[1]</value>
      <webElementGuid>e304d38c-361f-49da-b93e-f22858175a34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/select</value>
      <webElementGuid>58970b24-3f71-448a-9229-a938659ac1f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'Language' and @id = 'txtLanguage' and (text() = 'LanguageEnglishالعربيةEspañolFrançaisPortuguês' or . = 'LanguageEnglishالعربيةEspañolFrançaisPortuguês')]</value>
      <webElementGuid>f4894569-fd31-4c73-b8da-2c636df85a91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
