<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>UserSearch_Select_Co-TeacherRole_DropDown</name>
   <tag></tag>
   <elementGuidId>0c1df9c2-a957-4f4b-8109-dda31d908538</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SelectFilterRoles</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='SelectFilterRoles']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3bcaa25c-bef1-4d66-88ca-40de7c32ee4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SelectFilterRoles</value>
      <webElementGuid>12f971a2-f3a2-4cec-ace5-418dd58f0cca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SelectFilterRoles</value>
      <webElementGuid>25b6fb82-ca79-4074-82cf-baa95cc00c41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-valid ng-not-empty ng-dirty ng-valid-parse ng-touched</value>
      <webElementGuid>4df4e3fd-a8a4-4cce-b378-34dc11ec116c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>vm.filterRoleModel</value>
      <webElementGuid>ed40c8af-1c61-422c-a244-056a94fa2f1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-options</name>
      <type>Main</type>
      <value>item as item.RoleName | optionsTrim for item in vm.roles track by item.RoleId</value>
      <webElementGuid>b6498993-c8a8-479b-9b13-ae389ba8950e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-change</name>
      <type>Main</type>
      <value>vm.loadGrades();vm.searchForUser()</value>
      <webElementGuid>3f228330-7ff6-4244-ab9a-6fcf005f3afe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>87875f0f-3c8a-4726-959e-2fc248b170b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select RoleTeacherStudentAdminParentAcademic CoordinatorShadow TeacherHelp Teacherco adminGuest Studentacac newshadow tstudent 2cu admincustom admin 333Admin custom Oparent testSun risesunCo-TeacherMichael_teacher</value>
      <webElementGuid>ec32fee0-29b0-4c75-8da8-7a70e67bb8f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SelectFilterRoles&quot;)</value>
      <webElementGuid>568c1e66-1a75-4a07-a18a-237dc7904bf2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='SelectFilterRoles']</value>
      <webElementGuid>25882252-6ee8-476b-8dd6-934643d9c182</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='office365Div']/div/div/div/div/div/div[3]/div[2]/div[2]/div[2]/div/select</value>
      <webElementGuid>226bfc7c-6fbb-4c18-8936-bc2843ac9db9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='search'])[1]/following::select[2]</value>
      <webElementGuid>3c81acd5-0b9f-4d66-9c78-7f6aa70fe0f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='search'])[2]/preceding::select[2]</value>
      <webElementGuid>940afe14-e71d-40cf-bdac-294115e88054</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Name'])[1]/preceding::select[2]</value>
      <webElementGuid>87eddd50-af5d-486e-af62-c1ae5987025e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>2277d31b-cfd0-4aac-96f9-7370d587facd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'SelectFilterRoles' and @name = 'SelectFilterRoles' and (text() = 'Select RoleTeacherStudentAdminParentAcademic CoordinatorShadow TeacherHelp Teacherco adminGuest Studentacac newshadow tstudent 2cu admincustom admin 333Admin custom Oparent testSun risesunCo-TeacherMichael_teacher' or . = 'Select RoleTeacherStudentAdminParentAcademic CoordinatorShadow TeacherHelp Teacherco adminGuest Studentacac newshadow tstudent 2cu admincustom admin 333Admin custom Oparent testSun risesunCo-TeacherMichael_teacher')]</value>
      <webElementGuid>c1bb7c26-6464-4f53-91a4-f0821d8f9a4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
