<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>VerifyEnglishSubject_Text</name>
   <tag></tag>
   <elementGuidId>977a3547-de8a-47f6-920f-675f6e6c23b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ng-include > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//custom-tags-input[@id='txtSelectedRoles0']/div/div/ul/li/ti-tag-item/ng-include/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>16201bbd-e885-4dda-928a-8680dfa279f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-bind</name>
      <type>Main</type>
      <value>$getDisplayText()</value>
      <webElementGuid>f3774315-e45a-474d-98b0-dcb60d8f40b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>English</value>
      <webElementGuid>493442d4-eca7-4c76-b2a3-4568302c6fb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtSelectedRoles0&quot;)/div[@class=&quot;host&quot;]/div[@class=&quot;tags&quot;]/ul[@class=&quot;tag-list&quot;]/li[@class=&quot;tag-item&quot;]/ti-tag-item[1]/ng-include[1]/span[1]</value>
      <webElementGuid>c120dd50-df87-4b86-bc9b-b35b791707ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//custom-tags-input[@id='txtSelectedRoles0']/div/div/ul/li/ti-tag-item/ng-include/span</value>
      <webElementGuid>e3b4bed4-5902-4e98-9850-91dbf76be4d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subject :'])[1]/following::span[1]</value>
      <webElementGuid>44b98ca2-1ce7-4409-9368-5c8103fb9a2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Parent School'])[4]/following::span[1]</value>
      <webElementGuid>35c672f0-fac4-4dbc-9ec8-edd682f1b5eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/preceding::span[1]</value>
      <webElementGuid>0a14873c-1534-4a34-a3a1-d8b67db0efdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add a tag'])[1]/preceding::span[1]</value>
      <webElementGuid>114d2854-88e0-4496-ac20-b9fed5c2457d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-include/span</value>
      <webElementGuid>60932bf7-e5f9-4548-942d-5cf00c4a58f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'English' or . = 'English')]</value>
      <webElementGuid>1ddb3c21-5dd0-4fb8-b6d2-a5a8f8086a92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
