<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Administration_Button</name>
   <tag></tag>
   <elementGuidId>989ff0bc-ef50-43ca-b143-caf5afa124d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnAdministration > span.menu-item-parent.lms-whiteSpace-normal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btnAdministration']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5dcf57b0-ad85-4001-8502-fa7ff79194ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-item-parent lms-whiteSpace-normal</value>
      <webElementGuid>fbaed292-d800-4f02-b03c-6411fb485b8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Adminstration</value>
      <webElementGuid>406709df-3c40-4568-86e9-61ebf86949d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnAdministration&quot;)/span[@class=&quot;menu-item-parent lms-whiteSpace-normal&quot;]</value>
      <webElementGuid>b12156fd-c606-4974-9892-090dff57dcff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='btnAdministration']/span</value>
      <webElementGuid>c33bee06-52f3-47af-bf67-df28414f7751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administration Tools'])[1]/following::span[1]</value>
      <webElementGuid>b9b21faf-fffa-4ad2-8832-cf0f598073a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reports'])[1]/following::span[2]</value>
      <webElementGuid>082ffd49-b098-4119-bdf6-7bf7b4e893ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Roles &amp; Permissions'])[1]/preceding::span[1]</value>
      <webElementGuid>f9ddb0b5-f39e-4cc4-b868-4f50f3d7312b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Custom Fields'])[1]/preceding::span[2]</value>
      <webElementGuid>44a5ac86-a339-4d02-bf6e-e7b4f5552bf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Adminstration']/parent::*</value>
      <webElementGuid>ed93f59f-4aa1-4448-bfda-86d791904f73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/ul/li/a/span</value>
      <webElementGuid>c7b3ca6d-42a5-4fb1-861e-0470f4670790</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Adminstration' or . = 'Adminstration')]</value>
      <webElementGuid>b47efef4-6300-41c6-b2e6-089a7eeeddaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
